export const DEFAULT_ASSET_ALLOCATIONS = {
  CONS: {
    fixed_income_opportunities: 20.00,
    fixed_income_post_fixed: 55.00,
    fixed_income_inflation: 15.00,
    fixed_income_pre_fixed: 10.00,
    multimarket: 0.00,
    real_estate: 0.00,
    stocks: 0.00,
    stocks_long_biased: 0.00,
    private_equity: 0.00,
    foreign_fixed_income: 0.00,
    foreign_variable_income: 0.00,
    crypto: 0.00,
  },
  MOD: {
    fixed_income_opportunities: 15.00,
    fixed_income_post_fixed: 22.50,
    fixed_income_inflation: 30.00,
    fixed_income_pre_fixed: 15.00,
    multimarket: 0.00,
    real_estate: 5.00,
    stocks: 2.50,
    stocks_long_biased: 2.50,
    private_equity: 0.00,
    foreign_fixed_income: 2.50,
    foreign_variable_income: 5.00,
    crypto: 0.00,
  },
  ARROJ: {
    fixed_income_opportunities: 10.00,
    fixed_income_post_fixed: 15.00,
    fixed_income_inflation: 15.00,
    fixed_income_pre_fixed: 10.00,
    multimarket: 10.00,
    real_estate: 10.00,
    stocks: 5.00,
    stocks_long_biased: 5.00,
    private_equity: 4.50,
    foreign_fixed_income: 5.00,
    foreign_variable_income: 10.00,
    crypto: 0.50,
  },
  AGRESSIVO: {
    fixed_income_opportunities: 5.00,
    fixed_income_post_fixed: 10.00,
    fixed_income_inflation: 10.00,
    fixed_income_pre_fixed: 5.00,
    multimarket: 15.00,
    real_estate: 15.00,
    stocks: 10.00,
    stocks_long_biased: 10.00,
    private_equity: 5.00,
    foreign_fixed_income: 5.00,
    foreign_variable_income: 10.00,
    crypto: 5.00,
  },
} as const;

export const ASSET_CLASS_LABELS = {
  fixed_income_opportunities: 'Renda Fixa - Oportunidades',
  fixed_income_post_fixed: 'Renda Fixa - Pós Fixado',
  fixed_income_inflation: 'Renda Fixa - Inflação',
  fixed_income_pre_fixed: 'Renda Fixa - Pré Fixado',
  multimarket: 'Multimercado',
  real_estate: 'Imobiliário',
  stocks: 'Ações',
  stocks_long_biased: 'Ações - Long Biased',
  private_equity: 'Private Equity',
  foreign_fixed_income: 'Exterior - Renda Fixa',
  foreign_variable_income: 'Exterior - Renda Variável',
  crypto: 'Criptoativos',
} as const; 