export { useFinancialRecords, useGoalsAndEvents, useFinancialMetrics, useFinancialHighlights } from './useFinancialData'
export { useProjectionData } from './useProjectionData'
export { useGoals, useEvents, useGoalMutations, useEventMutations } from './useGoalsEventsManagement'
export { useInvestmentPlan, useInvestmentPlansByBrokerId, useInvestmentPlanMutations, usePlanAccess } from './useInvestmentPlan'
export { useInvestmentPolicy, usePolicySectionData, useInvestmentPolicyMutations, usePolicyCompleteness } from './useInvestmentPolicy'
export { useFinancialRecords as useFinancialRecordsManagement, useFinancialRecordsMutations } from './useFinancialRecordsManagement'
export { useCurrentUserProfile, useClientMutations, useClientsByBroker, useClientById, useBrokerAccess } from './useClientManagement'
export { useProfileData, usePlanCreation, usePlanCalculations, useAgeOptions } from './usePlanCreation'
export { useLinkedItems } from './useLinkedItems'
export { useLastActive } from './useLastActive'
export { usePerformanceData } from './usePerformanceData'
export { useStatementImports, useStatementImportsHistory } from './useStatementImports'

export type { GoalsStats, EventsStats } from './useGoalsEventsManagement'
export type { InvestmentPlanStats } from './useInvestmentPlan'
export type { PolicyStats } from './useInvestmentPolicy'
export type { FinancialRecordsStats } from './useFinancialRecordsManagement'
