-- Table for tracking statement imports from n8n
-- This table is used by n8n to track the status of statement imports
CREATE TABLE statement_imports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  n8n_execution_id TEXT NOT NULL UNIQUE,
  profile_id UUID NOT NULL,
  import_type TEXT NOT NULL CHECK (import_type IN ('consolidated', 'detailed')),
  status TEXT NOT NULL DEFAULT 'created' CHECK (status IN ('created', 'running', 'success', 'failed')),
  metadata JSONB DEFAULT '{}'::jsonb,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT statement_imports_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE
);

-- Indexes for better query performance
CREATE INDEX idx_statement_imports_profile_id ON statement_imports(profile_id);
CREATE INDEX idx_statement_imports_n8n_execution_id ON statement_imports(n8n_execution_id);
CREATE INDEX idx_statement_imports_status ON statement_imports(status);
CREATE INDEX idx_statement_imports_created_at ON statement_imports(created_at DESC);

-- Trigger to update updated_at
CREATE TRIGGER update_statement_imports_updated_at
    BEFORE UPDATE ON statement_imports
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Add comment to explain the table
COMMENT ON TABLE statement_imports IS 'Tracks statement imports from n8n automation. Used by n8n to update import status and track progress.';
COMMENT ON COLUMN statement_imports.n8n_execution_id IS 'Unique identifier generated by n8n to track the execution';
COMMENT ON COLUMN statement_imports.import_type IS 'Type of import: consolidated or detailed';
COMMENT ON COLUMN statement_imports.status IS 'Current status of the import: created, running, success, or failed';
COMMENT ON COLUMN statement_imports.metadata IS 'Additional JSON data that n8n can use to store extra information';
COMMENT ON COLUMN statement_imports.error_message IS 'Error message if the import failed';

